// Generated by CoffeeScript 1.7.1
(function() {
  window.KEY_CODE = {
    LEFT: 37,
    TOP: 38,
    RIGHT: 39,
    DOWN: 40,
    ENTER: 13,
    ESC: 27,
    KEY_CODE_F1: 112,
    KEY_CODE_F2: 113,
    KEY_CODE_F3: 114,
    KEY_CODE_F4: 115
  };

  window.MENU_TYPE = {
    PROFILE: 'stb-profile',
    NEW_PROFILE: 'new-stb-profile',
    PARENT_MENU: 'parent-menu'
  };

  window.CONFIG_ITEM_TYPES = {
    STRING: "string",
    BOOL: "bool",
    INT: "int",
    VARIANT: "variant"
  };

  window.CONFIG_MENU_VISUAL_TYPE = {
    LINEAR: 'linear',
    BLOCKS: 'blocks'
  };

}).call(this);
