// Generated by CoffeeScript 1.9.1
(function() {
  var __GUI__;

  if (typeof __GUI__ === "undefined" || __GUI__ === null) {

    /**
    *STUB method definitions for IDE hints.
    *
     */
    __GUI__ = (function() {
      function __GUI__() {}

      __GUI__.prototype.makeJsonMenu = function() {
        console.log('makeJsonMenu');
        return JSON.stringify({
          'default': 'menu-menu',
          'current': 'main-menu',
          'current_item_id': '',
          'profile_id': '',
          'profile': '',
          'items': {
            'main-menu': {
              count: 11,
              items: {
                'id-0': {
                  image: '',
                  title: 'ITEM 0',
                  type: MENU_TYPE.PARENT_MENU,
                  submenu: 'submenu-1'
                },
                'id-1': {
                  image: '',
                  title: 'ITEM 1',
                  type: MENU_TYPE.PROFILE,
                  'menu_type': 'stb-profile'
                },
                'id-2': {
                  image: '',
                  title: 'ITEM 2',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag',
                  'submodel': 'MAG250'
                },
                'id-3': {
                  image: '',
                  title: 'ITEM 3',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag',
                  'submodel': 'AuraHD'
                },
                'id-4': {
                  image: '',
                  title: 'ITEM 4',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-5': {
                  image: '',
                  title: 'ITEM 5',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-6': {
                  image: '',
                  title: 'ITEM 6',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-7': {
                  image: '',
                  title: 'ITEM 7',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-8': {
                  image: '',
                  title: 'ITEM 8',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-9': {
                  image: '',
                  title: 'ITEM 9',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-10': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-11': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-12': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-13': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-14': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-15': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-16': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-17': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-18': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-19': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-20': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                },
                'id-21': {
                  image: '',
                  title: 'ITEM 10',
                  type: MENU_TYPE.PROFILE,
                  'class': 'mag'
                }
              }
            },
            'submenu-1': {
              items: {
                'sub-id-0': {
                  image: '',
                  title: 'submenu-0',
                  type: MENU_TYPE.PROFILE,
                  "class": 'mag'
                }
              }
            }
          }
        });
      };

      __GUI__.prototype.loadProfile = function(id) {
        return console.log('Loading profile ' + id);
      };

      __GUI__.prototype.createProfile = function(classId, submodel, data) {
        console.log('Creating profile ' + classId + "->" + submodel + " with data " + JSON.stringify(data));
        return "random-profile-id";
      };

      __GUI__.prototype.saveProfile = function(id, data) {
        return console.log('Saving profile ' + id + " with data " + JSON.stringify(data));
      };

      __GUI__.prototype.removeProfile = function(id) {
        return console.log('Removing profile ' + id);
      };

      __GUI__.prototype.getProfileConfigOptions = function(id) {
        console.log('Loading profile ptions ' + id);
        return JSON.stringify([
          {
            'name': 'test-config-1',
            'title': 'title-1',
            'value': 'value-1',
            'comment': 'comment-1',
            'type': CONFIG_ITEM_TYPES.STRING
          }, {
            'name': 'test-config-2',
            'title': 'title-2',
            'value': true,
            'comment': 'comment-2',
            'type': CONFIG_ITEM_TYPES.BOOL
          }, {
            'name': 'test-config-3',
            'title': 'title-3',
            'value': 100,
            'comment': 'comment-3',
            'type': CONFIG_ITEM_TYPES.INT
          }, {
            'name': 'select-name-4',
            'title': 'select-title-4',
            'value': 2,
            'comment': 'select-comment-4',
            'type': CONFIG_ITEM_TYPES.VARIANT,
            'options': [
              {
                'title': 0,
                'value': 'text'
              }, {
                'title': 1,
                'value': 1
              }, {
                'title': 2,
                'value': 2
              }, {
                'title': 3,
                'value': 3
              }
            ]
          }
        ]);
      };

      __GUI__.prototype.getAppInfo = function() {
        return JSON.stringify({
          name: "yasem",
          version: 'version 0.1',
          copyright: 'Copyright 2014 by Maxim Vasilchuk'
        });
      };

      return __GUI__;

    })();
    window.__GUI__ = new __GUI__();
  }

}).call(this);
